### ISSUE TITLE
Allow override of loader options by resourceQuery

### ISSUE THREAD

**Issue by c0defre4k** [bhovhannes/svg-url-loader#133]
Similar to [svg-fill-loader](https://github.com/kisenka/svg-fill-loader)

E.g.:

```CSS
.selector {
  background-image: url(../../assets/ticket.svg?noquotes=false);
}
```

This overrides `noquotes`option from Webpack loader config.

It should be very easy by just merging webpacks ``this.resourceQuery`` with regular query in [Line 10](https://github.com/bhovhannes/svg-url-loader/blob/master/index.js#L10)
