### ISSUE TITLE
CSS is generated with "module.exports" JavaScript code

### ISSUE THREAD

**Issue by gajus** [bhovhannes/svg-url-loader#28]
My loader configuration:

``` js
loaders: [
  {
    test: /\.svg/,
    loader: 'svg-url'
  },
  {
    include: path.resolve(__dirname, './../client'),
    loader: 'babel',
    test: /\.js$/,
  },
  {
    loaders: [
      {
        loader: 'style',
        query: {
          sourceMap: 1
        }
      },
      {
        loader: 'css',
        query: {
          'modules': 1,
          'importLoaders': 1,
          'localIdentName': '[path]___[name]___[local]'
        }
      },
      'resolve-url',
      'sass'
    ],
    test: /\.css$/
  },
  {
    loader: 'file?name=[name].[ext]',
    test: /\.(ttf|otf|eot|svg|woff2?)(\?[a-z0-9]+)?$/
  }
]
```

The input:

``` css
.share-facebook {
  background-image: url('./facebook.svg');
}

.share-twitter {
  background-image: url('./twitter.svg');
}
```

The output:

``` css
.client-components-ArticleComponent-static-___styles___article .client-components-ArticleComponent-static-___styles___share-controls .client-components-ArticleComponent-static-___styles___share-facebook {
  background-image: url("data:image/svg+xml;charset=utf8,module.exports = __webpack_public_path__ + 'facebook.svg';");
}

.client-components-ArticleComponent-static-___styles___article .client-components-ArticleComponent-static-___styles___share-controls .client-components-ArticleComponent-static-___styles___share-twitter {
  background-image: url("data:image/svg+xml;charset=utf8,module.exports = __webpack_public_path__ + 'twitter.svg';");
}
```

Using:

``` json
"webpack": "^2.1.0-beta.20",
"svg-url-loader": "^1.1.0",
```
