### ISSUE TITLE
Load SVG fragments?

### ISSUE THREAD

**Issue by lemoustachiste** [bhovhannes/svg-url-loader#58]
Hi there, 

thanks for the good work.

I am trying to load fragments of SVG to my class, but it seems the output is incorrect:
```css
.icon--cat {
  background: url('./../assets/css-loaded/sprite.svg#icon-cat-outline');
}
```
and my webpack config:
```javascript
{
  test: /css-loaded\/[\S]+.svg/,
  loaders: ['svg-url-loader']
}
```
And this is the ouput I can see in Chrome:
```
background: url("data:image/svg+xml;charset=utf8,%3C!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.…%3E%3Csymbol viewBox='0 0 0 0' id='sprite'/%3E%3C/svg%3E"#icon-cat-outline);
```
which is ignored as invalid.

Is this even possible? If yes, is it supported by this loader?

Thanks for the help
