### ISSUE TITLE
Svg is abstracted from css file.

### ISSUE THREAD

**Issue by Evashasha** [bhovhannes/svg-url-loader#696]
Hi, I've met a problem that encoded svg code was abstracted from  its source css file.

The code in source file is like as following👇
```scss
$alert-primary-color-icon: red;
html{
    background-image: url(./assets/calendar.svg?fill=#{$alert-primary-color-icon});
}
```
After I run the command `npm run build`, output files in the destination directory 'dist' are like as following picture.
![截屏2023-08-10 16 54 38](https://github.com/bhovhannes/svg-url-loader/assets/20812374/b11e542a-8692-4aa6-b831-44734389df47)

The repository address is [https://github.com/Evashasha/resolve-url-loader-test](https://github.com/Evashasha/resolve-url-loader-test) .

I'm looking forward author's help.🌹🌹🌹
